GET http://localhost:3001/api/property

###
POST http://localhost:3001/api/property/new
Content-Type: application/json

{
    "address": "1 Manor Hills, Maynooth, Co. Kildare",
    "reserve": 500000,
    "currentBid": 450000,
    "currentBidderID":"100100",
    "estateAgent": "Ronan O'Neil",
    "saleDate": "10/10/2024",
    "sold":false
}

###
DELETE http://localhost:3001/api/property/delete/66f595b31528d63ab668c133

###
PUT http://localhost:3001/api/property/sold/66f589f58d665ed1c23a1ae7