const counties = [ //list of counties used when listing a property
    { value: 'County Carlow', label: 'County Carlow' },
    { value: 'County Cavan', label: 'County Cavan' },
    { value: 'County Clare', label: 'County Clare' },
    { value: 'County Cork', label: 'County Cork' },
    { value: 'County Donegal', label: 'County Donegal' },
    { value: 'County Dublin', label: 'County Dublin' },
    { value: 'County Galway', label: 'County Galway' },
    { value: 'County Kerry', label: 'County Kerry' },
    { value: 'County Kildare', label: 'County Kildare' },
    { value: 'County Kilkenny', label: 'County Kilkenny' },
    { value: 'County Laois', label: 'County Laois' },
    { value: 'County Leitrim', label: 'County Leitrim' },
    { value: 'County Limerick', label: 'County Limerick' },
    { value: 'County Longford', label: 'County Longford' },
    { value: 'County Louth', label: 'County Louth' },
    { value: 'County Mayo', label: 'County Mayo' },
    { value: 'County Meath', label: 'County Meath' },
    { value: 'County Monaghan', label: 'County Monaghan' },
    { value: 'County Offaly', label: 'County Offaly' },
    { value: 'County Roscommon', label: 'County Roscommon' },
    { value: 'County Sligo', label: 'County Sligo' },
    { value: 'County Tipperary', label: 'County Tipperary' },
    { value: 'County Waterford', label: 'County Waterford' },
    { value: 'County Westmeath', label: 'County Westmeath' },
    { value: 'County Wexford', label: 'County Wexford' },
    { value: 'County Wicklow', label: 'County Wicklow' }
];

export default counties;